version: '3.1'
services:
  db:
    image: postgres:9.6
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: tl_prod
      POSTGRES_DB: tl_prod
      POSTGRES_PASSWORD: ub3rl33tPassw0rDzMeng
    volumes:
      - ./postgres:/var/lib/postgresql/data
  cache:
    image: redis
    ports:
      - 16379:6379
