# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd2f785df1339d5dcaf6c73109c65d25f6a337ecab5afb971fb3f12c48a23624fe87e87dcc747d270a492043fbf1348f378949f571fbae3aaa4f93faf14daace

test:
  secret_key_base: 01c3192d3324cbb53155e592e7ce34f39cf3e29c3b6520b7220b528ea07efc972f879c7f0202ee9bbc9e0578952f235555ce5991f90a48841eb54f476c4c6937

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
